### ISSUE TITLE
Integration and two inverters.

### ISSUE THREAD

**Issue by sliwak03** [SilverFire/dessmonitor-homeassistant#15]
I have done the integration according to this project and it works fine. I currently have two inverters and by changing dessmonitor_api_uri in the secrets file I can monitor one or the other inverter. I have a question. Is it possible to integrate two inverters so that both are visible in home assistant?

**Comment by SilverFire** [comment]
Hi.

To have multiple inverters connected, you'll need to adjust the configuration to handle separate data streams and create unique sensors for each inverter. The recommended approach is to use Home Assistant's [Packages](https://www.home-assistant.io/docs/configuration/packages/) feature.


1.  **Enable Packages:** If you haven't already, enable packages in your Home Assistant `configuration.yaml` file. Add the following line:

    ```yaml
    homeassistant:
      packages: !include_dir_merge_named packages
    ```
    This tells Home Assistant to look for YAML files in a directory named `packages` and merge their contents into the configuration, using the filename as the key (e.g., `packages/inverter1.yaml` will be processed as a package named `inverter1`).

2.  **Identify API URLs for Each Inverter:** Repeat steps 3 and 4 from the "Preparation" section of this repo for *each* of your inverters. You will get a unique `Request URL` for each device (`devcode`, `pn`, `sn` parameters will differ).

3.  **Add API URLs to `secrets.yaml`:** Add a unique entry in your `secrets.yaml` file for the API URL of each inverter. Use descriptive names.

    ```yaml
    dessmonitor_api_uri_inverter1: https://web.dessmonitor.com/public/?sign=...&devcode=1234&pn=INVERTER1PN...
    dessmonitor_api_uri_inverter2: https://web.dessmonitor.com/public/?sign=...&devcode=5678&pn=INVERTER2PN...
    # Add an entry for each inverter you have
    ```

4.  **Create Package Files for Each Inverter:**
    *   Create a directory named `packages` in your Home Assistant configuration directory if it doesn't exist.
    *   Inside the `packages` directory, create a separate `.yaml` file for each inverter (e.g., `inverter1.yaml`, `inverter2.yaml`, `garage_inverter.yaml`, etc.).
    *   Each package file will contain the `rest` sensor and the `template` sensors *specifically for that inverter*.

5.  **Configure Each Package File:** For each inverter's package file (e.g., `packages/inverter1.yaml`), add the following structure:

    ```yaml
    # packages/inverter1.yaml
    sensor:
      - platform: rest
        # Give the REST sensor a unique name for this inverter
        name: Inverter Data Inverter1
        resource_template: !secret dessmonitor_api_uri_inverter1 # Reference the specific secret
        method: GET
        json_attributes_path: "$.dat.pars"
        json_attributes:
          - gd_
          - sy_
          - pv_
          - bt_
          - bc_
        scan_interval: 120 # Update every 2 minutes
        value_template: "OK"

    template:
      # Copy the relevant template configuration (e.g., from src/template.yaml, src/powmr.yaml, or src/eg4.yaml)
      # Paste it here under the 'template:' key
      # ***CRITICAL: Update all sensor names and the source entity with suffix `1` or `2***
      - trigger:
          - platform: state
            # REFERENCE THE UNIQUE REST SENSOR CREATED ABOVE
            entity_id: sensor.inverter_data_inverter1
        sensor:
          # Example for Grid Voltage
          - name: "Inverter1 Grid Voltage" # Give the sensor a unique, descriptive name
            unit_of_measurement: "V"
            device_class: voltage
            state_class: measurement
            # Reference the attributes from the unique REST sensor
            value_template: "{{ state_attr('sensor.inverter_data_inverter1', 'gd_')['0'] }}"
          # Example for Battery SOC
          - name: "Inverter1 Battery SOC"
            unit_of_measurement: "%"
            device_class: battery
            state_class: measurement
            # Reference the attributes from the unique REST sensor
            value_template: "{{ state_attr('sensor.inverter_data_inverter1', 'bt_')['0'] }}"
          # ... Add all other template sensors required for this inverter ...
          # Make sure ALL sensor names start with "Inverter1 " (or whatever prefix you choose)
          # and ALL value_template references point to 'sensor.inverter_data_inverter1'
    ```

    **Important Adaptations:**
    *   **Unique REST Sensor Name:** Change `name: Inverter Data` to something unique like `name: Inverter Data Inverter1` or `name: Inverter Data Garage`. Home Assistant will create an entity like `sensor.inverter_data_inverter1`.
    *   **Unique Secret Name:** Ensure `resource_template: !secret dessmonitor_api_uri_inverter1` points to the correct secret you defined in `secrets.yaml` for this specific inverter.
    *   **Copy Template Code:** Take the content from the `template.yaml` file that matches your inverter type (Sorotec/MuscleGrid, PowMr, EG4, etc.).
    *   **Paste into Package:** Paste the sensor definitions from the template file directly under the `template:` key in your package file.
    *   **Update Template Sensor Names:** **Crucially**, update the `name:` for *every* template sensor to include a prefix that identifies the inverter (e.g., `Grid Voltage` becomes `Inverter1 Grid Voltage`, `Battery SOC` becomes `Inverter1 Battery SOC`). This will create entities like `sensor.inverter1_grid_voltage`, `sensor.inverter1_battery_soc`, etc.
    *   **Update Template Source Entity:** **Crucially**, update the `entity_id:` in the `trigger` section of the template configuration to reference the unique REST sensor you created for this inverter (e.g., `entity_id: sensor.inverter_data_inverter1`). Also, update *all* `value_template` entries to reference the attributes of this unique REST sensor (e.g., `state_attr('sensor.inverter_data', 'gd_')['0']` becomes `state_attr('sensor.inverter_data_inverter1', 'gd_')['0']`).

6.  **Repeat for Each Inverter:** Create a package file (`inverter2.yaml`, etc.) for each additional inverter, following the same steps, ensuring unique names for the REST sensor, secrets, and all template sensors, and correctly referencing the specific REST sensor within the template section.

7.  **Update Dashboard Card:** Your dashboard card configuration will now need to reference the uniquely named sensors for the inverter you want to display (or you can create separate cards for each inverter).

    ```yaml
    type: custom:sunsynk-power-flow-card
    # ... other card config ...
    entities:
      # ... other entities ...
      inverter_voltage_154: sensor.inverter1_load_output_voltage # Use the new sensor name
      inverter_power_175: sensor.inverter1_load_power           # Use the new sensor name
      # inverter_status_59: sensor.inverter1_sunsynk_overall_state # Use the new sensor name (if applicable)
      battery_voltage_183: sensor.inverter1_battery_voltage     # Use the new sensor name
      battery_soc_184: sensor.inverter1_battery_soc             # Use the new sensor name
      battery_power_190: sensor.inverter1_battery_power         # Use the new sensor name
      grid_ct_power_172: sensor.inverter1_grid_power            # Use the new sensor name
      grid_voltage: sensor.inverter1_grid_voltage               # Use the new sensor name
      battery_current_191: sensor.inverter1_battery_current     # Use the new sensor name
      battery_current_direction: sensor.inverter1_battery_current_direction # Use the new sensor name
      # ... and so on for all relevant sensors ...
    # ... rest of card config ...
    ```

8.  **Restart Home Assistant:** Restart Home Assistant to load the new package configurations.
